repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.14
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
  - repo: local
    hooks:
      - id: tsc
        name: tsc
        entry: npm run typecheck
        language: node
        pass_filenames: false
      - id: eslint
        name: eslint
        entry: npm run lint
        language: node
        pass_filenames: false
      - id: prettier
        name: prettier
        entry: prettier --write --ignore-unknown
        language: node
        "types": [text]
        args: []
        require_serial: false
        additional_dependencies: ["prettier@3.6.2"]

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks
  autofix_prs: true
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: monthly
  skip: [tsc, eslint] # needs install, plus already covered by other ci
  submodules: false
exclude: |
  (?x)^(
    examples/.*|
    containers/ecr-viewer/seed-scripts/baseECR/.*|
    containers/message-parser/schema/.*.htm
  )$
